---
name: Bug Report
about: Report something that isn’t working
title: "[BUG] "
labels: bug
assignees: ''

---

## Description

What’s broken?

## Steps to Reproduce

1. Go to ...
2. Click ...
3. See error

## Expected Behavior

What should happen?

## Screenshots / Logs

(If applicable)
