---
name: "Feature Request"
about: Suggest a new feature or functionality
title: "[FEAT] "
labels: [feature]
assignees: []
---

## Summary

Briefly describe the feature you’d like to see.

## Motivation

Why is this feature important? What problem does it solve?

## Proposed Solution

How would you implement this? (optional)
