---
name: Refactor Request
about: Suggest an edit
title: "[REFACTOR] "
labels: enhancement
assignees: ''

---

## Summary

Briefly describe the feature you’d like to refactor.

## Acceptance Criteria

Define how success is measured.

- [ ]
- [ ]
- [ ]
